### ISSUE TITLE
发现一个Bug

### ISSUE THREAD

**Issue by Bvin** [ongakuer/ViewPagerHeaderScrollDemo#1]
第一个page滑到底，再切换到第二个page，由于第二个page没满一屏可以直接把隐藏的header完全拉下来，这时再回到一个page，由于第一个page的list是拉下到底的，所以如果我想看到前面的数据就要往下拉，这是就拉不动了。
如果是header是隐藏的就很顺畅，但是如果header全部展示出来了就会有问题。。。

**Comment by ongakuer** [comment]
@Bvin 修好了。 之前加入了TouchSlop判断差值是否可以滚动，一直在纠结是否需要。去除后滚动敏感度提高了（不过可能影响list item 的点击敏感度……）。
