### ISSUE TITLE
体验不好

### ISSUE THREAD

**Issue by xu6148152** [ongakuer/ViewPagerHeaderScrollDemo#2]
viewpager滚动和其内容的滚动并不会连续

我们公司做类似的效果，ios体验很好，但是android没做好。

可以看看这个吧,
https://github.com/kmshack/Android-ParallaxHeaderViewPager

因为上面这个采用的时headerview,所以会有局限性的，数据量小的话，体验也不好

**Comment by ongakuer** [comment]
@xu6148152  
 这个demo是这篇 http://relex.me/viewpagerheaderdemo/  的附属。ParallaxHeaderViewPager的原理和利弊也在其中有介绍。
（PS: 而且ParallaxHeaderViewPager有个偷懒的地方，当其中一个列表滑回顶部，同时也会把其他列表也一起滑回顶部）。

**Comment by xu6148152** [comment]
可以看下这个
https://github.com/ksoichiro/Android-ObservableScrollView

效果不错。

**Comment by ongakuer** [comment]
@xu6148152 
谢谢。 不过这个在ListView下也存在一些小问题…… 
https://github.com/ksoichiro/Android-ObservableScrollView/issues/3

不太精准的修正方案：
https://github.com/ongakuer/Android-ObservableScrollView/commit/ab6db0c2c1f4de073b9790e3c930bc0a84bd616f

**Comment by xu6148152** [comment]
我大概看了下这个东西，会有些BUG，但应该可以改。
你速度好快啊。立马出modify。。。

**Comment by ongakuer** [comment]
@xu6148152 
那个modify挺早以前就弄了……
