### ISSUE TITLE
如何能在滑动头部时，整体也自然滚动？

### ISSUE THREAD

**Issue by litao0621** [ongakuer/ViewPagerHeaderScrollDemo#3]
hi,首先感谢你提供这个项目，很喜欢。
我现在遇到这样一个问题，我得头部可能很长，占用了屏幕得四分之三，这样如果我向上滑动时，响应区域就很小，只有触摸那剩余得四分之一才能向上滑动，现在我想让它不管在哪里滑动都可以响应，想请教下我该如何下手，非常感谢。

**Comment by ongakuer** [comment]
你的需求如果要套用在这个demo上，改动应该会非常大。
拦截滚动触发的判断在下面这里。 你应该重新处理 ACTION_DOWN 等区域判断。
https://github.com/ongakuer/ViewPagerHeaderScrollDemo/blob/master/app/src/main/java/me/relex/viewpagerheaderscrolldemo/tools/ViewPagerHeaderHelper.java#L47

**Comment by litao0621** [comment]
感谢楼主得提示，还想问下，如果我不需要自然滚动，只是在头部中Touch事件y轴滑动(比如滑动1/3)后，头部自己自动滑动上面，有什么方法可以调用么？

**Comment by ongakuer** [comment]
应该没有什么方法调用吧。 原理还是一开始将待滑动View移到下面，然后监听手指触发区域，同时调用动画移动View，然后在ACTION_UP后，判断当前View移动距离是否到超过临界值，再调用动画完成View移动。

**Comment by litao0621** [comment]
问题差不多解决了，就是滑动头部时也能自然滚动就比较完美了，谢谢

**Comment by sd6352051** [comment]
希望还能帮我一个忙，header我直接调用headerFold这个方法来弄了，虽然滚动不是很自然，我先在需要加一个webviewfragemt,我按照scrollviewfragment来做单会报错，希望给些提示帮助，非常感谢
